Added method to create expiration date for Urls when is not premium.
StormITpl/TinyUrl pull request #24
Opened 2023-02-04 10:09 UTC by BartoszKarp

2023-02-04 15:28 UTC, RobertoJavaDev requested changes

2023-02-04 15:28 UTC, RobertoJavaDev commented on src/main/java/pl/stormit/tinyurl/domain/model/UrlExpiry.java
>      private Boolean isPremium = false;
Why do we set in advance in Entity that the user is not premium?

2023-02-04 15:28 UTC, RobertoJavaDev commented on src/main/java/pl/stormit/tinyurl/domain/model/UrlExpiry.java
> +    private Instant expirationDate = creationDate.plusSeconds(1209600);
Why do we set link expiry on Entity?
What if user will be premium?

2023-02-11 15:13 UTC, RobertoJavaDev requested changes

2023-02-11 15:13 UTC, RobertoJavaDev commented on src/main/java/pl/stormit/tinyurl/service/UrlExpiryService.java
> +    @Autowired
This annotation is not necessary

2023-02-11 15:13 UTC, RobertoJavaDev commented on src/main/java/pl/stormit/tinyurl/service/UrlExpiryService.java
> +        System.out.println("Start searching expired urls");
If we want to display information in the LOG, you should use a logger (e.g. slf4j ) instead of "System.out.println()"

2023-02-11 16:19 UTC, RobertoJavaDev commented on src/main/java/pl/stormit/tinyurl/domain/model/UrlExpiry.java
> +    private Instant expirationDate = creationDate.plusSeconds(60); //1209600
I think we should set expirationDate on service layer.

2023-02-11 16:24 UTC, BartoszKarp commented on src/main/java/pl/stormit/tinyurl/domain/model/Url.java
> +import lombok.*;
It was generated automaticly by intellij.

2023-02-11 16:35 UTC, RobertoJavaDev commented on src/main/java/pl/stormit/tinyurl/domain/model/Url.java
> +import lombok.*;
Yes, but you could change it in Intelij:
File > Settings > Project Settings > Code Style > Java > Imports > General > Class count to use import with '*'

2023-02-11 16:48 UTC, BartoszKarp commented on src/main/java/pl/stormit/tinyurl/domain/model/Url.java
> +import lombok.*;
what number should i choose?

2023-04-15 06:24 UTC, RobertoJavaDev requested changes

2023-04-15 06:24 UTC, RobertoJavaDev commented on src/main/java/pl/stormit/tinyurl/controller/UrlExpiryController.java
> +    public ResponseEntity<List<UrlExpiry>> getAllExpires() {
We should use Dto's instead of entities.

2023-04-15 06:24 UTC, RobertoJavaDev commented on src/main/java/pl/stormit/tinyurl/controller/UrlExpiryController.java
> +@RequestMapping(path = "api/v1/expiry")
The path should be plural

2023-04-15 06:24 UTC, RobertoJavaDev commented on src/main/java/pl/stormit/tinyurl/controller/UrlExpiryController.java
> +        List<UrlExpiry> urlExpiryList = urlExpiryService.getAllExpires();
The same - we should use Dto

2023-04-15 06:24 UTC, RobertoJavaDev commented on src/main/java/pl/stormit/tinyurl/domain/model/Url.java
> +import lombok.*;
I set twenty

2023-04-15 06:24 UTC, RobertoJavaDev commented on src/main/java/pl/stormit/tinyurl/domain/repository/UrlExpiryRepository.java
> +
Redundant white line

2023-04-15 06:24 UTC, RobertoJavaDev commented on src/main/java/pl/stormit/tinyurl/service/UrlExpiryService.java
> +    public UrlExpiry createUrlExpiryDate(Url url) {
We should use Dto

2023-04-15 06:24 UTC, RobertoJavaDev commented on src/main/java/pl/stormit/tinyurl/service/UrlExpiryService.java
> +        urlExpiry.setUrl(url);
Shouldn't we first search the "url" from the database to see if it exists ?

2023-04-15 06:24 UTC, RobertoJavaDev commented on src/main/java/pl/stormit/tinyurl/service/UrlExpiryService.java
> +    public List<UrlExpiry> getAllExpires() {
We should use Dto

2023-04-15 06:24 UTC, RobertoJavaDev commented on src/test/java/pl/stormit/tinyurl/service/UrlExpiryServiceTest.java
> +class UrlExpiryServiceTest {
Please correct the formatting of this class

2023-04-19 18:51 UTC, BartoszKarp commented on src/main/java/pl/stormit/tinyurl/controller/UrlExpiryController.java
> +@RequestMapping(path = "api/v1/expiry")
ok

2023-05-07 16:58 UTC, RobertoJavaDev approved these changes

2023-05-07 17:32 UTC, merged